language: csharp
mono: none
dotnet: latest
dist: trusty
before_install:
  - chmod +x ./restore.sh
  - chmod +x ./backend.sh
  - chmod +x ./frontend.sh
install:
  - ./restore.sh
script:
  - ./backend.sh
  - ./frontend.sh