version: '3.6'
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Pass@word
    ports:
     - "1433:1433"

  account:
    image: aiursoft/account:${TAG:-latest}
    build:
      context: .
      dockerfile: Account/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
      - "5000:5000"
    network_mode: "host"
      

  api:
    image: aiursoft/api:${TAG:-latest}
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose: 
      - 5001
    depends_on:
      - db
    network_mode: "host"

  cdn:
    image: aiursoft/cdn:${TAG:-latest}
    build:
      context: .
      dockerfile: CDN/Dockerfile
    ports:
      - "5002:80"

  developer:
    image: aiursoft/developer:${TAG:-latest}
    build:
      context: .
      dockerfile: Developer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose: 
      - 5004
    depends_on:
      - db
    network_mode: "host"

