version: '3.4'
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Pass@word
    ports:
     - "1433:1433"

  account:
    image: aiursoft/account:${TAG:-latest}
    build:
      context: .
      dockerfile: Account/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    depends_on:
      - db
