version: '3.4'
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Pass@word
    ports:
     - "1433:1433"

  account:
    image: aiursoft/account:${TAG:-latest}
    build:
      context: .
      dockerfile: Account/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - db

  api:
    image: aiursoft/api:${TAG:-latest}
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    depends_on:
      - db

  cdn:
    image: aiursoft/cdn:${TAG:-latest}
    build:
      context: .
      dockerfile: CDN/Dockerfile
    ports:
      - "5002:80"

  developer:
    image: aiursoft/developer:${TAG:-latest}
    build:
      context: .
      dockerfile: Developer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"
    depends_on:
      - db

